#!/bin/bash

#PBS -m abe

# Verbose mode.
#PBS -V

# Email for notification.
#PBS -M claudio.scheer@edu.pucrs.br

# Machine parameters:
# - nodes: number or name of nodes requested;
# - ppn: number of cores per node;
# - cluster-Atlantica / cluster-Cerrado / cluster-Amazonia: cluster name;
# - walltime: maximum allocation time;
#PBS -l nodes=cerrado13n:ppn=24+cerrado16n:ppn=24:cluster-Cerrado,walltime=999:00:00

# Output directory.
#PBS -d /home/claudio.scheer/Projects/mpi-ppgcc/master-slave

#PBS -r n
#PBS -j oe

echo Running on host `hostname`
echo
echo Initial Time: `date`
echo
echo Directory is `pwd`
echo
echo This jobs runs on the following nodes:
echo `cat $PBS_NODEFILE | uniq`
echo
echo JOB_ID:
echo `echo $PBS_JOBID`
echo --------------------------------------

# Export GCC 9.3.0.
source ~/opt/gcc-9.3.0/activate

rm -rf logs
mkdir -p logs/bubble-sort

n=3

# Bubble sort.
cd bubble-sort
for ((i = 1; i <= $n; i++)); do
    make sequential vector-size=96000 > ../logs/bubble-sort/sequential-$size-$i.txt 2>&1
done

for ((i = 1; i <= $n; i++)); do
    make mpi vector-size=96000 delta=3000 np=32 > ../logs/bubble-sort/mpi-$np-$size-$i.txt 2>&1
done
cd -

echo --------------------------------------
echo Final Time: `date`
